#define PRODUCT_VERSION_STR				L"1.0.0.0"
#define PRODUCT_VERSION_SHORT_STR1		L"1.0.0"
#define PRODUCT_VERSION_SHORT_STR2		L"0.0"
#define PRODUCT_FILE_VER_STR_DOT		L"1.0.0.100"
#define PRODUCT_MAJOR_VERSION			1 //_MAJORVER_
#define PRODUCT_MINOR_VERSION			0 //_MINORVER_
#define PRODUCT_REVISION				0 //_SUBMINVER_
#define PRODUCT_BUILD_NUMBER			100 //_BUILDNUM_	

